[workspace]
channels = ["conda-forge"]
name = "neuro-impl-hub"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.dev.dependencies]
python = "3.12.*"
jupyterlab = ">=4.4.4,<5"
pre-commit = ">=4.2.0,<5"
black = ">=25.1.0,<26"
rich = ">=14.0.0,<15"

[environments]
default = ["dev"]
